runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/v1/.*
  script: main.application
- url: /(.+)
  static_files: app/\1
  upload: app/.*
- url: /
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"